services:
  - type: web
    name: agentic-backend
    runtime: node
    rootDirectory: Backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://akshaysanaka07_db_user:HZMvpmlJrQlHDpWJ@cluster0.vl01zdp.mongodb.net/?appName=Cluster0
      - key: PORT
        value: 5000
  - type: web
    name: agentic-frontend
    runtime: static
    rootDirectory: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://agentic-ai-1-fk2m.onrender.com/api
